rk3588s_s: media_profile: fix some config for cts
Test: CtsCameraTestCases
android.hardware.camera2.cts.RecordingTest

error log:
junit.framework.AssertionFailedError: Video size 4096x3072 for profile
ID 1 must be one of the camera device supported video size!

Signed-off-by: Wang Panzhenzhuan <randy.wang@rock-chips.com>
Change-Id: I04be83255d2962f35fe9be139d5e1dd9fc24a9a1
(cherry picked from commit 18629bcd1178d5425095eb26310ed4da9e97519f)